api:
  base_url: "https://api.openai.com/v1"
  key: ${OPENAI_API_KEY}

models:
  judge: "gpt-4o"
  guessers:
    # - "gpt-4" # $30.00/1M input tokens, $60.00/1M output tokens
    # - "gpt-4-turbo" # $10.00/1M input tokens, $30.00/1M output tokens
    # - "gpt-4o" # $5.00/1M input tokens, $15.00/1M output tokens
    # - "gpt-3.5-turbo" # $3.00/1M input tokens, $6.00/1M output tokens
    - "gpt-4o-mini" # $0.15/1M input tokens, $0.50/1M output tokens

game:
  character_to_guess: ""
  max_questions: 30
  num_rounds: 3
